import React, { useState } from 'react'
import useDashboard from '../../../hooks/useDashboard'
import { Loader } from '../../Common/Loader/Loader'
import { ChartHeader, ReportsByMonthChart, StatCard, TopFiveReportPieChart } from './DashboardComponents'
import { monthTypes } from '../../../constants/monthTypes'

function Dashboard() {
  const [selectedMonth, setSelectedMonth] = useState(5)
  const { loading, dashboardOverview, topReportTemplates, monthlyReports, recentReports } = useDashboard(selectedMonth)
  if (loading) return <Loader />
  return (
    <div>
      <h1 className="text-4xl font-bold mb-4">
        Dashboard
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <StatCard title="Total Users" value={dashboardOverview?.usersCount} />
        <StatCard title="Total Reports" value={dashboardOverview?.reportsCount} />
        <StatCard title="Total Report Templates" value={dashboardOverview?.reportTemplatesCount} />
      </div>

      <div className="grid gap-10 my-12">
        <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
          <ChartHeader
            title="Reports Generated by Month"
            subtitle="Report count grouped by template"
          />
          <div className="flex justify-end mb-4">
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(Number(e.target.value))}
              className="border rounded-lg px-3 py-2"
            >
              {monthTypes.map((month) => (
                <option key={month.value} value={month.value}>{month.label}</option>
              ))}
            </select>
          </div>

          <ReportsByMonthChart data={monthlyReports} />
        </div>
        <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
          <ChartHeader
            title="Top 5 Report Templates"
            subtitle="Distribution based on report usage"
          />
          <TopFiveReportPieChart data={topReportTemplates} />
        </div>
      </div>
    </div>
  )
}

export default Dashboard